FROM node:22-alpine

WORKDIR /app

# Copie des fichiers de configuration
COPY package.json .
COPY package-lock.json .
COPY tailwind.config.js .
COPY postcss.config.js .

# Installation des dépendances
RUN npm ci

# Mise à jour de browserslist
RUN npx browserslist@latest --update-db

# Copie du code source
COPY ./src ./src
COPY ./public ./public

# Exposition du port
EXPOSE 3000

# Commande de démarrage
CMD ["npm", "run", "start"]