export const EXTRA_DECK_LABELS = [
    "Fusion Monster",
    "Pendulum Effect Fusion Monster",
    "Synchro Monster",
    "Synchro Tuner Monster",
    "Synchro Pendulum Effect Monster",
    "XYZ Monster",
    "XYZ Pendulum Effect Monster",
    "Link Monster",
];

export const MAIN_DECK_LABELS = [
    "normal monster",
    "normal tuner monster",
    "effect monster",
    "tuner monster",
    "pendulum tuner effect monster",
    "flip effect monster",
    "spirit monster",
    "union effect monster",
    "gemini monster",
    "toon monster",
    "ritual monster",
    "ritual effect monster",
    "pendulum effect monster",
    "pendulum flip monster",
    "pendulum flip effect monster",
    "pendulum normal monster",
    "pendulum effect ritual monster",
    "pendulum effect union monster",
    "pendulum effect spirit monster",
    "normal spell",
    "field spell",
    "equip spell",
    "continuous spell",
    "quick-play spell",
    "ritual spell",
    "normal trap",
    "continuous trap",
    "counter trap",
];